### ISSUE TITLE
loading 'detector config file' again failed.

### ISSUE THREAD

**Issue by zhanzhang3** [AdvancedPhotonSource/rsMap3D#7]
On the GUI interface, after all the field filled in, if I reload the "detector config file", either a different one or the same one, I got the following error before program terminated: 

NoneType: None
Traceback (most recent call last):
  File "C:\Users\zhanzhang\AppData\Local\anaconda3\envs\rsmap3d\Lib\site-packages\rsMap3D\gui\input\usesxmldetectorconfig.py", line 138, in _currentDetectorChanged
    self.updateROIandNumAvg()
  File "C:\Users\zhanzhang\AppData\Local\anaconda3\envs\rsmap3d\Lib\site-packages\rsMap3D\gui\input\usesxmldetectorconfig.py", line 293, in updateROIandNumAvg
    detector = self.detConfig.getDetectorById(str(self.currentDetector))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhanzhang\AppData\Local\anaconda3\envs\rsmap3d\Lib\site-packages\rsMap3D\datasource\DetectorGeometry\detectorgeometrybase.py", line 79, in getDetectorById
    raise DetectorConfigException("Detector " +
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rsMap3D.exception.rsmap3dexception.DetectorConfigException: Detector  not found in detector config file

**Comment by zhanzhang3** [comment]
I think I figured out the problem -- when changing to a different detector file, Detector List will be cleared first, at which time, _currentDetectorChanged function will be triggered and it tries to set ROI etc again.  Need to check if the list is empty or not here -- if it is empty, skip the ROI setting.
